pin pytest, pytest-cov, sphinx dev-requirements
In PR #234, all the python 3.7 builds (but only .37) failed on flake8 step of linting.

File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'

Most probable cause is the recent release of pytest-cov-4.0.0  and upgrades/mismatch in its transitive dependencies. 
Pinning so builds at least run in same config as week ago and failing CI is not blocking PRs