tests: fix failures from bump of transitive deps to urllib3 2.X
- remove remove test_function_import_without_return_type_wrong_code

The entire logic of the test was based on scenario that server returns response of HTTP 204 No Content (which ends with HTTP Header) with some content in HTTP Body, which is breaking the HTTP protocol logic itself.

The Responses package generated such weird simulated response and was parsed with urllib 1.X in previous versions of Requests, but now, with being compatible with urllib3 2.x, breaking changes were introduced within this transitive dependency.

On the requests side, the bump to same urllib3 2.x means test failures with error:

requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(10 bytes read, -10 more expected)', IncompleteRead(10 bytes read, -10 more expected))

- test_update_entity

Same rationale, removed invalid body for expected HTTP 204 simulated response

Additional info:

getsentry/responses#636
https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html

RFC 2616  - HTTP 1.1 - 10.2.5 - 204 No Content
https://datatracker.ietf.org/doc/html/rfc2616#section-10.2.5